source "/home/fortunate/zishh/Core/Packages/files.zsh"
source "/home/fortunate/zishh/Core/Packages/folders.zsh"
source "/home/fortunate/zishh/Core/Packages/sed.zsh"
source "/home/fortunate/zishh/Core/Packages/shell.zsh"
source "/home/fortunate/zishh/Core/Packages/valet.zsh"
source "/home/fortunate/zishh/Core/Packages/wordpress.zsh"
