source "/home/fortunate/zishh/App/Functions/File.zsh"
source "/home/fortunate/zishh/App/Functions/File.zsh"
source "/home/fortunate/zishh/App/Functions/Folder.zsh"
source "/home/fortunate/zishh/App/Functions/Folder.zsh"
source "/home/fortunate/zishh/App/Functions/Goto.zsh"
source "/home/fortunate/zishh/App/Functions/Goto.zsh"
source "/home/fortunate/zishh/App/Functions/Host.zsh"
source "/home/fortunate/zishh/App/Functions/Host.zsh"
