source "/home/fortunate/zeesh/App/Functions/File.zsh"
source "/home/fortunate/zeesh/App/Functions/Folder.zsh"
source "/home/fortunate/zeesh/App/Functions/Goto.zsh"
source "/home/fortunate/zeesh/App/Functions/Host.zsh"
source "/home/fortunate/zeesh/App/Functions/Zeesh.zsh"
